#child gitlab-ci

image: maven:latest

stages:
- build-package-maven

build-package maven 1/2:
  stage: build-package-maven
  script:
  - mvn compile
  only:
  - master

build-package maven 2/2:
  stage: build-package-maven
  script:
  - mvn clean package
  only:
  - master
